parameters:
    pim_catalog.entity.abstract_product.class:             Pim\Component\Catalog\Model\AbstractProduct
    pim_catalog.entity.product.class:                      Pim\Component\Catalog\Model\Product
    pim_catalog.entity.product_model.class:                Pim\Component\Catalog\Model\ProductModel
    pim_catalog.entity.product_unique_data.class:          Pim\Component\Catalog\Model\ProductUniqueData
    pim_catalog.entity.association.class:                  Pim\Component\Catalog\Model\ProductAssociation
    pim_catalog.entity.product_model_association.class:    Pim\Component\Catalog\Model\ProductModelAssociation
    pim_catalog.entity.completeness.class:                 Pim\Component\Catalog\Model\Completeness
    pim_catalog.entity.category.class:                     Pim\Bundle\CatalogBundle\Entity\Category
    pim_catalog.entity.category_translation.class:         Pim\Bundle\CatalogBundle\Entity\CategoryTranslation
    pim_catalog.entity.group.class:                        Pim\Bundle\CatalogBundle\Entity\Group
    pim_catalog.entity.group_translation.class:            Pim\Bundle\CatalogBundle\Entity\GroupTranslation
    pim_catalog.entity.metric.class:                       Pim\Component\Catalog\Model\Metric
    pim_catalog.entity.product_price.class:                Pim\Component\Catalog\Model\ProductPrice
