parameters:
    pim_catalog.model.product.interface:                Pim\Component\Catalog\Model\ProductInterface
    pim_catalog.model.product_model.interface:          Pim\Component\Catalog\Model\ProductModelInterface
    pim_catalog.model.value.interface:                  Pim\Component\Catalog\Model\ValueInterface
    pim_catalog.model.association.interface:            Pim\Component\Catalog\Model\AssociationInterface
    pim_catalog.model.completeness.interface:           Pim\Component\Catalog\Model\CompletenessInterface
    pim_catalog.model.category.interface:               Pim\Component\Catalog\Model\CategoryInterface
    pim_catalog.model.group.interface:                  Pim\Component\Catalog\Model\GroupInterface
    pim_catalog.model.metric.interface:                 Pim\Component\Catalog\Model\MetricInterface
    pim_catalog.model.product_price.interface:          Pim\Component\Catalog\Model\ProductPriceInterface
    pim_catalog.model.category_translation.interface:         Pim\Component\Catalog\Model\CategoryTranslationInterface
    pim_catalog.model.group_translation.interface:            Pim\Component\Catalog\Model\GroupTranslationInterface
